name: lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [ 'opened', 'synchronize' ]

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.22.2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@26e57d6b340778c2983cd61775bc7e8bb41d002a # v2.19.0
        with:
            args: -tests ./...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
      - name: Autobuild
        uses: github/codeql-action/autobuild@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          args: --timeout 1h
