name: lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [ 'opened', 'synchronize' ]

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # 4.1.0
        with:
          go-version: 1.19
      - name: Run Gosec Security Scanner
        uses: securego/gosec@a89e9d5a7acb4457f3891ac18532b142b1bf9221 # v2.17.0
        with:
            args: -tests ./...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # 2.21.5
      - name: Autobuild
        uses: github/codeql-action/autobuild@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # 2.21.5
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # 2.21.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          args: --timeout 1h