name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ 'opened', 'synchronize' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Go test
        run: |
          go test ./...