name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ 'opened', 'synchronize' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # 4.1.0
        with:
          go-version: 1.19
      - name: Go test
        run: |
          go test ./...